/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kidfolk_androidRDP_AndroidRDPActivity */

#ifndef _Included_org_kidfolk_androidRDP_AndroidRDPActivity
#define _Included_org_kidfolk_androidRDP_AndroidRDPActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    getenv
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_getenv
  (JNIEnv *, jclass);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    setUsername
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_setUsername
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    setPassword
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_setPassword
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    rdp_connect
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_rdp_1connect
  (JNIEnv *, jclass, jstring, jint, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    rdp_main_loop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_rdp_1main_1loop
  (JNIEnv *, jclass);

/*
 * Class:     org_kidfolk_androidRDP_AndroidRDPActivity
 * Method:    getBitmapBytesFormNative
 * Signature: (IIII[Ljava/lang/Byte;)[Ljava/lang/Byte;
 */
JNIEXPORT jobjectArray JNICALL Java_org_kidfolk_androidRDP_AndroidRDPActivity_getBitmapBytesFormNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
