/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kidfolk_androidRDP_RdesktopNative */

#ifndef _Included_org_kidfolk_androidRDP_RdesktopNative
#define _Included_org_kidfolk_androidRDP_RdesktopNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kidfolk_androidRDP_RdesktopNative
 * Method:    getenv
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kidfolk_androidRDP_RdesktopNative_getenv
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
