/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kidfolk_androidRDP_RdesktopNative */

#ifndef _Included_org_kidfolk_androidRDP_RdesktopNative
#define _Included_org_kidfolk_androidRDP_RdesktopNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kidfolk_androidRDP_RdesktopNative
 * Method:    getenv
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kidfolk_androidRDP_RdesktopNative_getenv
  (JNIEnv *, jclass);

/*
 * Class:     org_kidfolk_androidRDP_RdesktopNative
 * Method:    setUsername
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_RdesktopNative_setUsername
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_kidfolk_androidRDP_RdesktopNative
 * Method:    setPassword
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kidfolk_androidRDP_RdesktopNative_setPassword
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_kidfolk_androidRDP_RdesktopNative
 * Method:    rdp_connect
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_org_kidfolk_androidRDP_RdesktopNative_rdp_1connect
  (JNIEnv *, jclass, jstring, jint, jstring, jstring, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
